defaults:
  - model_checkpoint
  - model_summary
  - learning_rate_monitor
  - early_stopping
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: False
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
