# @package _global_

defaults:
  - model: patchless_nnunet
  - trainer: patchless_nnunet
  - paths: default
  - extras: default
  - hydra: patchless_nnunet
  - _self_

task_name: "predict"

tags: ["predict"]

# input folder containing data for inference
input_folder: ???

# output folder to save predictions
output_folder: ???

# passing checkpoint path is necessary for prediction
ckpt_path: ???

# whether to use test time augmentation
tta: True

# whether to overwrite existing predictions in the output folder
overwrite_existing: True

pin_memory: True

num_workers: 12

hydra:
  output_subdir: null
  run:
    dir: ${output_folder}

paths:
  output_dir: ${output_folder}

model:
  save_predictions: True
  tta: ${tta}
